### ISSUE TITLE
Explorer uses the wrong path for database GET

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#19]
So it gets to the DB list GET and that works fine:

    https://management.azure.com/subscriptions/{sub}/resourceGroups/Default-SQL-WestUS/providers/Microsoft.Sql/servers/qfhzpobzl2/databases?api-version=2014-04-01

returns

```json
{
  "value": [
    {
      "id": "/subscriptions/{sub}/resourceGroups/Default-SQL-WestUS/providers/Microsoft.Sql/servers/qfhzpobzl2/databases/master",
      "name": "master",
      "type": "Microsoft.Sql/servers/databases",
      etc...
```

But when I click on a specific DB, it gets really confused and queries this path:

    https://management.azure.com/subscriptions/{sub}/resourceGroups/Default-SQL-WestUS/providers/Microsoft.Sql/servers/master/databases/qfhzpobzl2?api-version=2014-04-01

Notice how it has `/servers/master/databases/qfhzpobzl2`, reversing the server name and db name! The ID that got returned from the list GET is actually correct.

**Comment by ahmelsayed** [comment]
the reason for this bug is that we would generate the element Url for every element based on the metadata, **not** on its parent.

for example when you click on a site, we go check the metadata for that element and we get back a `GET` url that looks like 

```
https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroup}/providers/Microsoft.Web/sites/{siteName}
```

then we walk the tree up asking each node to fill in it's value. Nodes know their `resourceName` in the metadata tree, that is their url segment name basically, so the current node fills in `{siteName}` the resource group node fills in `{resourceGroup}` and so on.

the problem with spec-less elements is that all their nodes are called `{name}` and so the nodes get confused about which `{name}` to fill in exactly.

I forgot why I had it that way to begin with, but I think I didn't want to make assumptions about the shape of the element Url being a strict superset of it's parent's url. For a fix I will add an actual filled in Url object to each element in the tree that their children will append their names to instead.
