### ISSUE TITLE
ARMExplorer is broken in IE

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/ARMExplorer#2]
Totally busted. Like the templates are not expanding, and it's displaying things like `{{ treeControl.get_selected_branch().label }}`.

**Comment by ahmelsayed** [comment]
I can't repro that!
It might be IE cashing the home page because it's just an html static page, even though I explicitly turned off caching, but IE usually ignores that. Then when it tried to get the javascript files it got 302 to login page but it won't redirect then because the home page loaded from the cache.
I will change the home page to cshtml to prevent any cashing behavior from browsers.

**Comment by davidebbo** [comment]
I can't repro today. Maybe it was some caching issue. Let's close for now.
